"""Shared SQLAlchemy declarative base + column helpers.

All module models share this one ``Base`` (and therefore one ``MetaData``) so cross-module
foreign keys resolve and Alembic autogenerate sees the whole schema. Models are still
organized per module (Django-app style) under ``app/modules/<name>/models.py``.
"""

from __future__ import annotations

from sqlalchemy import Column, DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase

# Stable constraint/index names → clean, reproducible autogenerated migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Column:
    """UUID primary key defaulting to Postgres ``gen_random_uuid()``."""
    return Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at() -> Column:
    return Column(DateTime(timezone=True), nullable=False, server_default=func.now())


def updated_at() -> Column:
    return Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
