"""interviews_initial

Revision ID: 0639fd8fc802
Revises: 4b807b8d307a
Create Date: 2026-09-06 11:34:30.772498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0639fd8fc802'
down_revision: Union[str, None] = '4b807b8d307a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_candidate_id', sa.UUID(), nullable=False),
    sa.Column('candidate_stage_run_id', sa.UUID(), nullable=True),
    sa.Column('hunar_call_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('vendor_status', sa.Text(), nullable=True),
    sa.Column('normalized_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("normalized_status IN ('QUEUED','SCHEDULED','CALLING','CONNECTED','COMPLETED','NO_ANSWER','RETRY_SCHEDULED','FAILED','CANCELLED')", name=op.f('ck_calls_normalized_status_valid')),
    sa.ForeignKeyConstraint(['candidate_stage_run_id'], ['candidate_stage_runs.id'], name=op.f('fk_calls_candidate_stage_run_id_candidate_stage_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_candidate_id'], ['job_candidates.id'], name=op.f('fk_calls_job_candidate_id_job_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    op.create_table('stage_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_stage_run_id', sa.UUID(), nullable=False),
    sa.Column('structured_result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript_summary', sa.Text(), nullable=True),
    sa.Column('result_schema_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_stage_run_id'], ['candidate_stage_runs.id'], name=op.f('fk_stage_results_candidate_stage_run_id_candidate_stage_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_results'))
    )
    op.create_table('call_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('vendor_status', sa.Text(), nullable=True),
    sa.Column('normalized_status', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('business','infrastructure')", name=op.f('ck_call_attempts_kind_valid')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_attempts_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_attempts')),
    sa.UniqueConstraint('call_id', 'attempt_number', name=op.f('uq_call_attempts_call_id_attempt_number'))
    )
    op.create_table('evaluation_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stage_result_id', sa.UUID(), nullable=False),
    sa.Column('stage_criteria_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_criteria_id'], ['stage_criteria.id'], name=op.f('fk_evaluation_scores_stage_criteria_id_stage_criteria'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_result_id'], ['stage_results.id'], name=op.f('fk_evaluation_scores_stage_result_id_stage_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_scores')
    op.drop_table('call_attempts')
    op.drop_table('stage_results')
    op.drop_table('calls')
    # ### end Alembic commands ###
