"""webhooks_initial

Revision ID: 2ab1b645c6c1
Revises: 0639fd8fc802
Create Date: 2026-09-06 11:34:31.366822
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2ab1b645c6c1'
down_revision: Union[str, None] = '0639fd8fc802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.Text(), server_default='hunar', nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_webhook_events_call_id_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'dedup_key', name=op.f('uq_webhook_events_provider_dedup_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
