"""workflows_initial

Revision ID: d51f1aef10bf
Revises: f21ab38693d2
Create Date: 2026-09-06 11:34:29.611632
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd51f1aef10bf'
down_revision: Union[str, None] = 'f21ab38693d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_templates_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_templates'))
    )
    op.create_table('workflow_template_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_template_versions_template_id_workflow_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_template_versions')),
    sa.UniqueConstraint('template_id', 'version', name=op.f('uq_workflow_template_versions_template_id_version'))
    )
    op.create_table('calling_policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('allowed_days', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('earliest_call_time', sa.Time(), nullable=True),
    sa.Column('last_call_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('retry_interval_hours', sa.Integer(), server_default='6', nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_attempts >= 0', name=op.f('ck_calling_policies_max_attempts_nonneg')),
    sa.CheckConstraint('retry_interval_hours >= 0', name=op.f('ck_calling_policies_retry_interval_nonneg')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_calling_policies_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_calling_policies_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calling_policies'))
    )
    op.create_table('job_workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_workflows_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['workflow_templates.id'], name=op.f('fk_job_workflows_source_template_id_workflow_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_workflows')),
    sa.UniqueConstraint('job_id', name=op.f('uq_job_workflows_job_id'))
    )
    op.create_table('workflow_stage_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_version_id', sa.UUID(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('execution_type', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("execution_type IN ('ai','human','system')", name=op.f('ck_workflow_stage_templates_exec_type_valid')),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], name=op.f('fk_workflow_stage_templates_template_version_id_workflow_template_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage_templates')),
    sa.UniqueConstraint('template_version_id', 'stage_order', name=op.f('uq_workflow_stage_templates_template_version_id_stage_order'))
    )
    op.create_table('job_workflow_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_workflow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_job_workflow_versions_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_workflow_id'], ['job_workflows.id'], name=op.f('fk_job_workflow_versions_job_workflow_id_job_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_workflow_versions')),
    sa.UniqueConstraint('job_workflow_id', 'version', name=op.f('uq_job_workflow_versions_job_workflow_id_version'))
    )
    op.create_table('job_workflow_stages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('execution_type', sa.Text(), nullable=False),
    sa.Column('information_requirements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('transition_policy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('calling_policy_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("execution_type IN ('ai','human','system')", name=op.f('ck_job_workflow_stages_exec_type_valid')),
    sa.ForeignKeyConstraint(['calling_policy_id'], ['calling_policies.id'], name=op.f('fk_job_workflow_stages_calling_policy_id_calling_policies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_workflow_version_id'], ['job_workflow_versions.id'], name=op.f('fk_job_workflow_stages_job_workflow_version_id_job_workflow_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_workflow_stages')),
    sa.UniqueConstraint('job_workflow_version_id', 'stage_order', name=op.f('uq_job_workflow_stages_job_workflow_version_id_stage_order'))
    )
    op.create_table('hunar_agent_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_workflow_stage_id', sa.UUID(), nullable=True),
    sa.Column('hunar_agent_id', sa.Text(), nullable=False),
    sa.Column('configuration_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_workflow_stage_id'], ['job_workflow_stages.id'], name=op.f('fk_hunar_agent_configs_job_workflow_stage_id_job_workflow_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hunar_agent_configs'))
    )
    op.create_table('stage_criteria',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_workflow_stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('numeric','rule')", name=op.f('ck_stage_criteria_kind_valid')),
    sa.ForeignKeyConstraint(['job_workflow_stage_id'], ['job_workflow_stages.id'], name=op.f('fk_stage_criteria_job_workflow_stage_id_job_workflow_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_criteria'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_criteria')
    op.drop_table('hunar_agent_configs')
    op.drop_table('job_workflow_stages')
    op.drop_table('job_workflow_versions')
    op.drop_table('workflow_stage_templates')
    op.drop_table('job_workflows')
    op.drop_table('calling_policies')
    op.drop_table('workflow_template_versions')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
