"""candidates_initial

Revision ID: 4b807b8d307a
Revises: d51f1aef10bf
Create Date: 2026-09-06 11:34:30.195499
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b807b8d307a'
down_revision: Union[str, None] = 'd51f1aef10bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_candidates_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_table('job_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('current_stage_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_job_candidates_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['job_workflow_stages.id'], name=op.f('fk_job_candidates_current_stage_id_job_workflow_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_candidates_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_candidates')),
    sa.UniqueConstraint('job_id', 'candidate_id', name=op.f('uq_job_candidates_job_id_candidate_id'))
    )
    op.create_table('candidate_stage_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_workflow_stage_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','BLOCKED','READY','SCHEDULED','IN_PROGRESS','AWAITING_RESULT','NEEDS_REVIEW','COMPLETED','FAILED','CANCELLED','SKIPPED')", name=op.f('ck_candidate_stage_runs_status_valid')),
    sa.ForeignKeyConstraint(['job_candidate_id'], ['job_candidates.id'], name=op.f('fk_candidate_stage_runs_job_candidate_id_job_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_workflow_stage_id'], ['job_workflow_stages.id'], name=op.f('fk_candidate_stage_runs_job_workflow_stage_id_job_workflow_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_stage_runs'))
    )
    op.create_table('candidate_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_candidate_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_stage_run_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_candidate_id'], ['job_candidates.id'], name=op.f('fk_candidate_facts_job_candidate_id_job_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_stage_run_id'], ['candidate_stage_runs.id'], name=op.f('fk_candidate_facts_source_stage_run_id_candidate_stage_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_facts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_facts')
    op.drop_table('candidate_stage_runs')
    op.drop_table('job_candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
